source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

target 'sdkdemo-objc' do
  use_frameworks!

  pod 'RBSDKPlayer', :path => '../' 
  pod 'YoutubePlayer-in-WKWebView', :git => 'https://github.com/rhinobird/YoutubePlayer-in-WKWebView.git'
  pod 'Brightcove-Player-Core/dynamic', '~> 6.4'
end
