source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

target 'sdkdemo-swift' do
  use_frameworks!

  pod 'RBSDKPlayer', :path => '../' 
  pod 'Brightcove-Player-Core', '~> 6.3'
end
